; AMX Mod X plugins — modo CSDM (ReDeathmatch)

; Admin Base
admin.amxx
admincmd.amxx
adminhelp.amxx
adminslots.amxx
multilingual.amxx

; Menus
menufront.amxx
cmdmenu.amxx
plmenu.amxx
mapsmenu.amxx
pluginmenu.amxx

; Chat / Messages
adminchat.amxx
antiflood.amxx
scrollmsg.amxx
imessage.amxx
adminvote.amxx

; Map related
nextmap.amxx
mapchooser.amxx
timeleft.amxx

; Configuration
pausecfg.amxx
statscfg.amxx

; Counter-Strike
statsx.amxx
miscstats.amxx
csstatsx_sql.amxx

; send info to api
live_scoreboard.amxx
live_killfeed.amxx

; reserva 1 slot para o HLTV
slots_reserve.amxx

; --- ReDeathmatch (CSDM) ---
ReDeathmatch.amxx
redm_spawns.amxx
