; AMX Mod X plugins — modo GunGame (regg)

; Admin Base
admin.amxx
admincmd.amxx
adminhelp.amxx
adminslots.amxx
multilingual.amxx

; Menus
menufront.amxx
cmdmenu.amxx
plmenu.amxx
mapsmenu.amxx
pluginmenu.amxx

; Chat / Messages
adminchat.amxx
antiflood.amxx
scrollmsg.amxx
imessage.amxx
adminvote.amxx

; Map related
nextmap.amxx
mapchooser.amxx
timeleft.amxx

; Configuration
pausecfg.amxx
statscfg.amxx

; Counter-Strike
statsx.amxx
miscstats.amxx
csstatsx_sql.amxx

; send info to api
live_scoreboard.amxx
live_killfeed.amxx

; reserva 1 slot para o HLTV
slots_reserve.amxx

; --- regg GunGame ---
regg_core.amxx
regg_balancer.amxx
regg_block_send_wpn_anim.amxx
regg_controller.amxx
regg_informer.amxx
regg_leader.amxx
regg_map_cleaner.amxx
regg_mapmanager.amxx
regg_motd.amxx
regg_notify.amxx
regg_show_winner.amxx
regg_store_points.amxx
regg_vote.amxx
regg_warmup.amxx
