global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cs16-api
    metrics_path: /metrics
    basic_auth:
      username: __METRICS_USER__
      password: __METRICS_PASS__
    static_configs:
      - targets: ['api:3000']

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: nginxlog
    static_configs:
      - targets: ['nginxlog-exporter:4040']

  - job_name: node
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
