global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cs16-api
    metrics_path: /metrics
    basic_auth:
      username: __METRICS_USER__
      password: __METRICS_PASS__
    static_configs:
      - targets: ['api:3000']

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
